name: boreyko_flu_lab3
description: "A new flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.0.1 
  form_builder_validators: ^11.1.2 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
